---
build:
  stage: build
  script:
    - 'mvn clean deploy -U -DskipTests'
    - 'docker tag docker.mobike.io/$CI_PROJECT_PATH docker.mobike.io/$CI_PROJECT_PATH/$CI_BUILD_REF_NAME:`git rev-parse --short=8 HEAD`'
    - 'docker tag docker.mobike.io/$CI_PROJECT_PATH docker.mobike.io/$CI_PROJECT_PATH/$CI_BUILD_REF_NAME'
    - 'docker push docker.mobike.io/$CI_PROJECT_PATH/$CI_BUILD_REF_NAME:`git rev-parse --short=8 HEAD`'
    - 'docker image rm docker.mobike.io/$CI_PROJECT_PATH/$CI_BUILD_REF_NAME:`git rev-parse --short=8 HEAD`'
    - 'docker image rm docker.mobike.io/$CI_PROJECT_PATH/$CI_BUILD_REF_NAME'
    - 'docker image rm docker.mobike.io/$CI_PROJECT_PATH'
release:
  stage: build
  script:
    - 'rm -f release.properties pom.xml.releaseBackup'
    - 'mvn release:prepare -B'
    - 'rm -f release.properties pom.xml.releaseBackup'
  only:
    - /^release\/.*$/
  when: manual
deploy:
  stage: build
  script:
    - 'mvn clean deploy -DskipTests -U -Dci.commit.tag=$CI_COMMIT_TAG'
    - 'docker image rm docker.mobike.io/$CI_PROJECT_PATH:$CI_COMMIT_TAG'
    - 'docker image rm docker.mobike.io/$CI_PROJECT_PATH'
  only:
    - tags
